#!/bin/bash
usage="Timeshifter A tool to make a Timeshift effect on animations/gifs/videos.

Usage: timeshifter [-options] source.gif|source/

Where options can be
-h		show this help
-v		verbose
-slices <int>	select the amount of slices (defaults to the height)
-o output/	set output folder, defaults to source output without .gif extension
-g <delay>	Make a GIF named as <output>_timerelapsed.gif, 5 == 50ms
-e folder	extract the gif as single frames to the given folder and then exits" 

vflag='no'
sflag='no'
aflag='no'
slices=0
output='output/'
gflag='no'
eflag='no'
extraction=''
while getopts "ahvs:o:g:e:" opt; do
	case $opt in
		h)
			echo "$usage">&2
			exit 1
			;;
		v)
			vflag='yes'
			;;
		s)	
			sflag='yes'
			slices=$OPTARG
			;;
		g)	
			gflag='yes'
			delay=$OPTARG
			;;
		a)
			aflag='yes'
			;;
		o)
			output=$OPTARG
			clean="${output::-1}"
			;;
		e)
			eflag='yes'		
			extraction=$OPTARG
			;;
		:)
			echo "Option -$OPTARG requires an argument." >&2
			exit 1
			;;
	esac
done

shift $(expr $OPTIND - 1 )

source=$1
if [ $output = "output/" ]; then
	if [[ -f $source ]]; then
		output="${source::-4}"/
		clean="${source::-4}"
	elif [[ -d $source ]]; then
		echo "You need to select an explicit output folder when using folder as source"
		exit 1
	fi
fi

if [ $eflag = yes ]; then
	if [ ! -d $extraction ]; then
	    mkdir -p $extraction;
	fi;
	convert -coalesce $source -colorspace sRGB -alpha on PNG32:$extraction/%03d.png
	echo "Extraction Finished"
	exit 0
fi


if [ $vflag = yes ]; then
	echo "Source: $source"	
	echo "Output: $output"
	if [ $gflag = yes ]; then
		echo "Gif: ${clean}_timeshifted.gif"
	fi
fi

rm -rf _timeshifter_temp_dir_/
mkdir -p _timeshifter_temp_dir_/
if [ ! -d $output ]; then
    mkdir -p $output
fi

if [[ -d $source ]]; then
	if [ $vflag = yes ]; then
		echo "Copyng..."
	fi
	cp $source/*.png _timeshifter_temp_dir_/
elif [[ -f $source ]]; then
	if [ $vflag = yes ]; then
		echo "Spliting..."
	fi
	convert -coalesce $source -colorspace sRGB -alpha on PNG32:_timeshifter_temp_dir_/%03d.png
fi

cp _timeshifter_temp_dir_/*.png $output

frames=$(ls -1 _timeshifter_temp_dir_/| wc -l)
height=$(identify -format "%H" _timeshifter_temp_dir_/000.png)

if [ $sflag = no ]; then
	slices=$frames
fi

slice_height=$(expr $height / $slices)

if [ $vflag = yes ]; then
	echo "Frames: $frames"
	echo "Height: $height"
	echo "Slice Height: $slice_height"
	echo "Slices: $slices"
fi

if [ $vflag = yes ]; then
	echo "Processing..."
fi
start=`date +%s`

timeshifter _timeshifter_temp_dir_/ $output $frames $slices

end=`date +%s`
runtime=$((end-start))
echo "Time elapsed ${runtime}secs"

#cleans all
rm -rf _timeshifter_temp_dir_/ 
echo "Timeshifter Finished"

if [ $aflag = yes ]; then
	animate -delay 5 $output/*.png
fi

if [ $gflag = yes ]; then
	echo "Generating gif..."
	convert -delay $delay -loop 0 $output/*.png "${clean}_timeshifted.gif"
	eog "${clean}_timeshifted.gif"
fi